### ISSUE TITLE
Add support for --max-warnings

### ISSUE THREAD

**Issue by Senderek** [EngageSoftware/eslint-formatter-azure-devops#128]
As a part of the issue: https://github.com/eslint/eslint/issues/14881
Eslint team added the ability for formatters to support `--max-warnings`.

Would it be possible to add this feature?

I can provide the code, but I do not have the power to push new branches or create PR.

**Comment by bdukes** [comment]
Yes, I'm open to this code contribution. Thanks!

**Comment by Senderek** [comment]
How can I contribute?
I prepared a branch and I will be happy to create a PR.
`remote: Permission to EngageSoftware/eslint-formatter-azure-devops.git denied`

**Comment by bdukes** [comment]
You can [fork this repository](https://github.com/EngageSoftware/eslint-formatter-azure-devops/fork), which will create a copy under your ownership. Push your branch to that repository, and then you can [create a pull request](https://github.com/EngageSoftware/eslint-formatter-azure-devops/compare) from your branch to this repository's `master` branch. If you can't get that working, you can run `git format-patch origin/master`, which will create `.patch` files for each commit, and then you should be able to upload those `.patch` files to this issue and I can apply them to the repository.

Hope it helps!

**Comment by Senderek** [comment]
https://github.com/EngageSoftware/eslint-formatter-azure-devops/pull/130
